### ISSUE TITLE
Can't load model

### ISSUE THREAD

**Issue by Xiaohui9607** [xuyxu/Ensemble-Pytorch#43] opened 2021-02-25 02:59 UTC
RT

**Comment by xuyxu** [comment] 2021-02-25 03:03
Hi @Xiaohui9607, the latest version with PR #41 adds this. You can install the package from source:

``` bash
git clone https://github.com/xuyxu/Ensemble-Pytorch.git
cd Ensemble-Pytorch
pip install .
```

**Comment by Xiaohui9607** [comment] 2021-02-25 03:33
no, it doesn't, you need to "fit" a model before you can load the checkpoint:
fail: 
`
model = VotingClassifier(estimator=model_wrapper,  # your deep learning model
                        n_estimators=10)
# {Ensemble_Method_Name}_{Base_Estimator_Name}_{n_estimators}
filename = "{}_{}_{}_ckpt.pth".format(type(model).__name__,
                                      model.base_estimator_.__name__,
                                      model.n_estimators)
io.load(model, "/home/golf/Downloads")
save_dir = os.path.join("/home/golf/Downloads", filename)`

success:
`model = VotingClassifier(estimator=model_wrapper,  # your deep learning model
                        n_estimators=10)
import os
# {Ensemble_Method_Name}_{Base_Estimator_Name}_{n_estimators}
filename = "{}_{}_{}_ckpt.pth".format(type(model).__name__,
                                      model.base_estimator_.__name__,
                                      model.n_estimators)
model.set_optimizer("Adam",
                    lr=learning_rate,
                    weight_decay=weight_decay)
model.fit(train_loader,
          epochs=1)
io.load(model, "/home/golf/Downloads")`

**Comment by xuyxu** [comment] 2021-02-25 03:38
Thanks, I will fix this ;-)

If you want to use the model on the fly, could you check if methods like `pickle.dump` help?

**Comment by xuyxu** [comment] 2021-02-25 03:43
@all-contributors please add @Xiaohui9607  for bug

**Comment by xuyxu** [comment] 2021-02-25 07:50
The problem is that `torchensemble` does not register all base estimators into the ensemble during the instantiation. Instead, each of them will be inserted into the ensemble when calling the `fit` method. As a result, if we want to reload params into a newly-declared model, all keys in the `state_dict` are missing.

 Thanks for your report, we will fix this.

**Closed** 2021-02-25 08:43 UTC
Labels: bug
